config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  # TODO: - remove or add this line locally.
  # mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  authenticated :user, ->(user) { user.admin? } do
    mount DelayedJobWeb, at: '/delayed_job'
  end

  devise_for :users, path: :auth, controllers: { sessions: 'users/sessions',
                                                 confirmations: 'users/confirmations',
                                                 registrations: 'users/registrations',
                                                 unlocks: 'users/unlocks',
                                                 passwords: 'users/passwords' }

  get 'request_consent', to: 'home#request_consent'
  post 'grant_consent', to: 'home#grant_consent'
  get 'after_registration', to: 'home#after_registration'
  get 'system_events', to: 'home#system_events'

  resources :team_diagnostic_letters
  resources :diagnostics do
    resources :diagnostic_questions
  end
  resources :diagnostic_questions
  resources :entitlements
  resources :invitations do
    collection do
      get 'claim', to: 'invitations#claim'
      post 'process_claim', to: 'invitations#process_claim'
      post 'resend', to: 'invitations#resend'
    end
  end
  resources :organizations
  resources :tenants
  resources :translations, as: :application_translations, alias: :translations
  resources :users do
    resources :grants
  end
  resources :team_diagnostics do
    resources :participants do
      collection do
        get :define_import, to: 'participants#define_import'
        post :create_import, to: 'participants#create_import'
      end
      member do
        post :disqualify, to: 'participants#disqualify'
        post :restore, to: 'participants#restore'
        post :activate, to: 'participants#activate'
        post :resend_invitation, to: 'participants#resend_invitation'
      end
    end
    member do
      get 'wizard/:step', to: 'team_diagnostics#wizard', as: 'wizard'
      get 'export.:format', to: 'team_diagnostics#export', as: 'export'
      get 'report/:report_id.:format', to: 'team_diagnostics#report', as: 'report'
      post :deploy, to: 'team_diagnostics#deploy'
      post :complete, to: 'team_diagnostics#complete'
      post :generate_report, to: 'team_diagnostics#generate_report'
      delete :cancel, to: 'team_diagnostics#cancel'
    end
    resources :team_diagnostic_questions
    resources :team_diagnostic_letters
  end
  resources :participants
  resources :diagnostic_surveys do
    collection do
      get :not_found, to: 'diagnostic_surveys#not_found'
    end
    member do
      post :complete, to: 'diagnostic_surveys#complete'
    end
  end
  # Error pages
  %w[404 422 500].each do |code|
    get code, to: 'errors#show', code:
  end
end

app/models/concerns/participants/state_machine.rb
# frozen_string_literal: true

# Participant Concern
module Participants
  # Participant state machine logic
  module StateMachine
    extend ActiveSupport::Concern

    included do
      include AASM

      aasm column: :state do
        state :approved, initial: true
        state :active
        state :completed
        state :disqualified

        event :activate do
          transitions from: :approved, to: :active, after: :after_activation, if: :activation_permitted?
        end

        event :complete do
          transitions from: :active, to: :completed
        end

        event :disqualify do
          transitions from: %i[approved active], to: :disqualified, after: :after_disqualification
        end

        event :requalify do
          transitions from: :disqualified, to: :approved
        end

        event :cancel do
          transitions from: :active, to: :approved, after: :after_cancel
        end
      end

      # def permitted_state_events
      # aasm.events(permitted: true).map(&:name)
      # end

      # def permitted_states
      # aasm.states(permitted: true).map(&:name)
      # end

      def activation_permitted?
        valid? && team_diagnostic&.deployed?
      end

      def after_activation
        return false unless approved? || active?

        create_active_survey
      end

      def after_disqualification
        cancel_surveys
      end

      def after_cancel
        cancel_surveys
      end
    end
  end
end

app/models/participant.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: participants
#
#  id                 :uuid             not null, primary key
#  team_diagnostic_id :uuid             not null
#  state              :string           default("approved"), not null
#  email              :string           not null
#  phone              :string
#  title              :string
#  first_name         :string           not null
#  last_name          :string           not null
#  locale             :string           not null
#  timezone           :string           not null
#  notes              :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  metadata           :json
#
class Participant < ApplicationRecord
  ### Constants
  ALLOWED_PARAMS = %i[email phone title first_name last_name locale timezone notes metadata].freeze
  PARTICIPATING_STATES = %i[approved active completed].freeze

  ### Concerns
  include Participants::StateMachine

  ### Validations
  validates :state, presence: true
  validates :email, presence: true, uniqueness: { scope: :team_diagnostic_id }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :locale, presence: true
  validates :timezone, presence: true
  validate :team_diagnostic_is_active

  ### Scopes
  scope :participating, -> { where(state: PARTICIPATING_STATES) }

  ### Associations
  belongs_to :team_diagnostic
  has_many :diagnostic_surveys, dependent: :destroy

  ### Class Methods

  ### Instance Methods

  def event_description
    full_name
  end

  def needs_attention?
    pending_actions.any?
  end

  def pending_actions
    actions = []
    actions << 'Invalid'.t unless valid?
    actions << 'Please invite this participant'.t if pending_invitation?
    actions
  end

  def pending_invitation?
    !active? && team_diagnostic.deployed?
  end

  def full_name
    [title, first_name, last_name].join(' ')
  end

  def active_survey
    diagnostic_surveys.completed.order(created_at: :desc).first ||
      diagnostic_surveys.active.order(created_at: :desc).first
  end

  def create_active_survey
    cancel_surveys
    diagnostic_surveys
      .create(team_diagnostic:, locale:)
      .activate!
  end

  def survey_completed?
    diagnostic_surveys.completed.any?
  end

  def survey_active?
    active_survey.present?
  end

  def cancel_surveys
    diagnostic_surveys.active.each(&:cancel!)
  end

  def team_diagnostic_is_active
    team_diagnostic&.setup? || team_diagnostic&.deployed?
  end

  def send_reminder
    return false unless active_survey.present?

    active_survey.send_reminder_message
  end

  def progress_pct
    if active_survey
      (active_survey.progress * 100.0).round(0)
    else
      0.0
    end
  end
end

app/controllers/participants_controller.rb
# frozen_string_literal: true

# Participant management controller
class ParticipantsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_team_diagnostic
  before_action :set_participant, only: %i[show edit update destroy disqualify restore activate]
  after_action :verify_authorized

  # GET /participants
  # GET /participants.json
  def index
    authorize Participant
    @participants = record_scope.order('last_name ASC, first_name ASC')
    @current_page = 'All'.t
  end

  # GET /participants/1
  # GET /participants/1.json
  # def show
  # authorize @participant
  # @current_page = 'Participant'.t
  # end

  # GET /participants/new
  def new
    @service = ParticipantServices::Creator.new(user: current_user, team_diagnostic: @team_diagnostic, params:)
    @participant = @service.participant
    authorize @participant
  end

  # GET /participants/1/edit
  def edit
    @service = ParticipantServices::Updater.new(user: current_user, id: @participant.id, params:)
    @participant = @service.participant
    authorize @participant
  end

  # POST /participants
  # POST /participants.json
  def create
    @service = ParticipantServices::Creator.new(user: current_user, team_diagnostic: @team_diagnostic, params:)
    authorize @service.participant

    respond_to do |format|
      created = @service.call
      @participant = @service.participant
      if created
        format.html { redirect_to new_team_diagnostic_participant_path(team_diagnostic_id: @participant.team_diagnostic.id), notice: 'Participant was added'.t }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    @service = ParticipantServices::Updater.new(user: current_user, id: @participant.id, params:)
    authorize @service.participant

    respond_to do |format|
      updated = @service.call
      @participant = @service.participant
      if updated
        format.html { redirect_to wizard_team_diagnostic_path(id: @participant.team_diagnostic.id, step: TeamDiagnostics::Wizard::PARTICIPANTS_STEP), notice: 'Participant was updated'.t }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @service = ParticipantServices::Updater.new(user: current_user, id: @participant.id, params: {})
    authorize @service.participant
    @service.destroy!
    respond_to do |format|
      format.html { redirect_to wizard_team_diagnostic_path(id: @participant.team_diagnostic.id, step: TeamDiagnostics::Wizard::PARTICIPANTS_STEP), notice: 'Participant was removed'.t }
      format.json { head :no_content }
    end
  end

  # POST /participants/1/disqualify
  def disqualify
    @service = ParticipantServices::Updater.new(user: current_user, id: @participant.id, params: {})
    authorize @service.participant
    @service.disqualify!
    respond_to do |format|
      format.html { redirect_to wizard_team_diagnostic_path(id: @service.participant.team_diagnostic.id, step: TeamDiagnostics::Wizard::PARTICIPANTS_STEP), notice: 'Participant was disqualified'.t }
      format.json { head :no_content }
    end
  end

  # POST /participants/1/disqualify
  def restore
    @service = ParticipantServices::Updater.new(user: current_user, id: @participant.id, params: {})
    authorize @service.participant
    @service.restore!
    respond_to do |format|
      format.html { redirect_to wizard_team_diagnostic_path(id: @service.participant.team_diagnostic.id, step: TeamDiagnostics::Wizard::PARTICIPANTS_STEP), notice: 'Participant was restored'.t }
      format.json { head :no_content }
    end
  end

  # POST /participants/1/activate
  def activate
    @service = ParticipantServices::Updater.new(user: current_user, id: @participant.id, params: {})
    authorize @service.participant
    activated = @service.activate!
    notice = activated ? 'Participant was activated'.t : 'Participant could not be activated'.t
    respond_to do |format|
      format.html { redirect_to wizard_team_diagnostic_path(id: @service.participant.team_diagnostic.id, step: TeamDiagnostics::Wizard::PARTICIPANTS_STEP), notice: }
      format.json { head :no_content }
    end
  end

  def define_import
    set_team_diagnostic
    authorize @team_diagnostic
    @service = ParticipantServices::Importer.new(user: @current_user, team_diagnostic: @team_diagnostic, data: nil, options: {})
    @current_page = 'Import'.t
    @error = false
    @current_page = 'Import Participants'.t
  end

  def create_import
    set_team_diagnostic
    authorize @team_diagnostic
    @service = ParticipantServices::Importer.new(user: @current_user, team_diagnostic: @team_diagnostic, data: params[:participants], options: {})
    @service.call
    if @service.valid?
      redirect_to wizard_team_diagnostic_path(id: @team_diagnostic.id, step: TeamDiagnostics::Wizard::PARTICIPANTS_STEP), notice: 'Participants were imported successfully'.t
    else
      @errors = true
      render :define_import
    end
  end

  def resend_invitation
    set_team_diagnostic
    set_participant
    authorize @participant
    set_diagnostic_survey
    @diagnostic_survey.send_invitation_message
    redirect_to wizard_team_diagnostic_path(id: @team_diagnostic.id, step: TeamDiagnostics::Wizard::PARTICIPANTS_STEP), notice: 'Invitation resent'.t
  end

  private

  def record_scope
    @team_diagnostic ? policy_scope(@team_diagnostic.participants) : policy_scope(Participant)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_participant
    @participant = record_scope.find(params[:id])
  end

  def set_diagnostic_survey
    @diagnostic_survey = @participant.diagnostic_surveys
                                     .active
                                     .where(team_diagnostic_id: @team_diagnostic.id)
                                     .last
  end

  # Only allow a list of trusted parameters through.
  # def participant_params
  # allowed_params = policy(@participant || Participant).allowed_params
  # params.require(:participant).permit(*allowed_params)
  # end

  def set_team_diagnostic
    if params[:team_diagnostic_id]
      policy = TeamDiagnosticPolicy::Scope.new(current_user, TeamDiagnostic)
      @team_diagnostic = policy.resolve.where(id: params[:team_diagnostic_id]).first
    else
      @participant ? @participant.team_diagnostic : (raise ActiveRecord::RecordNotFound)
    end
  end
end

app/helpers/participants_helper.rb
# frozen_string_literal: true

# Participant view helpers
module ParticipantsHelper
  def participant_state_badge_class(participant)
    if participant.needs_attention?
      'warning'
    else
      {
        'approved' => 'info',
        'active' => 'success',
        'disqualified' => 'danger'
      }.fetch('participant_state', 'info')
    end
  end
end

app/views/participants/_breadcrumbs.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb bg-light shadow-sm rounded-3">
    <li class="breadcrumb-item"><%= link_to('Dashboard'.t, root_path) %></li>
    <% if @team_diagnostic %>
      <% if @team_diagnostic.setup? %>
        <li class="breadcrumb-item"><%= link_to( @team_diagnostic.name, wizard_team_diagnostic_path(id: @team_diagnostic.id, step: TeamDiagnostics::Wizard::PARTICIPANTS_STEP )) %></li>
      <% else %>
        <li class="breadcrumb-item"><%= link_to( @team_diagnostic.name, team_diagnostic_path(@team_diagnostic )) %></li>
      <% end %>
      <li class="breadcrumb-item"><%= link_to('Participants'.t, team_diagnostic_participants_path(team_diagnostic_id: @team_diagnostic.id )) %></li>
    <% end %>
    <li class="breadcrumb-item active" aria-current="page"><%= ( @current_page || params[:action].humanize.t )%> </li>
  </ol>
</nav>

app/views/participants/_define_import.html.erb
<div class="row">
  <div class="col">
    <h1><%= 'Import Participants'.t %></h1>
  </div>
</div>

<div class="row">
  <div class="col">
    <p class="lead">
      <%= sanitize('team_diagnostic--participants--define_import-help'.t, tags: %w{ul li b strong}) %>
    </p>
  </div>
</div>

<div class="d-flex justify-content-center">
  <div class="">
    <table class="table">
      <thead>
        <tr>
          <th><%= 'Title'.t %></%=></th>
          <th><%= 'First Name'.t %></th>
          <th><%= 'Last Name'.t %></th>
          <th><%= 'Email'.t %></th>
          <th><%= 'Phone Number'.t %></th>
          <th><%= 'Locale'.t %></th>
          <th><%= 'Time Zone'.t %></th>
          <th><%= 'Metadata'.t %></th>
        </th>
      </thead>
      <tbody>
        <tr>
          <td>Ms.</td>
          <td>Jane</td>
          <td>Smith</td>
          <td>jsmith@example.com</td>
          <td>+1 555-555-5555</td>
          <td>en</td>
          <td>CST</td>
          <td><tt>{ 'code': 'abc' }</tt></td>
        </tr>
        <tr>
          <td>Mr.</td>
          <td>John</td>
          <td>Doe</td>
          <td>jdoe@example.com</td>
          <td></td>
          <td>en</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td>Pat</td>
          <td>Doe</td>
          <td>pdoe@example.com</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div clas="col">
    <%= form_tag(create_import_team_diagnostic_participants_path(team_diagnostic_id: @team_diagnostic.id), multipart: true, method: :post) do |f| %>
      <div class="form-group">
        <%= file_field_tag :participants, class: 'form-control-lg', id: 'participant_file_select' %>
      </div>
      <%= submit_tag('Import'.t, class: 'btn btn-primary', id: 'participant_import_submit', disabled: true) %>
      <%= link_to('Back'.t, wizard_team_diagnostic_path(id: @team_diagnostic.id, step: TeamDiagnostics::Wizard::PARTICIPANTS_STEP), class: 'btn btn-light') %>
    <% end %>
  </div>
</div>

app/views/participants/_form.html.erb
<% remote = defined?(remote) ? remote : false %>

<%= bootstrap_form_for(participant, local: !remote, html: { role: 'form'}) do |f| %>
  <%= render partial: 'shared/form_errors', locals: { subject: participant } %>

  <%= hidden_field_tag :team_diagnostic_id, participant.team_diagnostic_id %>

  <div class="form-row">
    <div class="col-sm-2">
      <%= f.text_field :title, label: 'Prefix'.t, autofocus: true %>
    </div>
    <div class="col-sm-5">
      <%= f.text_field :first_name, label: 'First Name'.t, required: true %>
    </div>
    <div class="col-sm-5">
      <%= f.text_field :last_name, label: 'Last Name'.t, required: true %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <%= f.email_field :email, label: 'Email'.t, required: true %>
    </div>
    <div class="col-sm-6">
      <%= f.telephone_field :phone, label: 'Phone Number'.t, required: false %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <%= f.select :locale, locales_for_select(participant), label: 'Locale'.t, required: true %>
    </div>
    <div class="col-sm-6">
      <%= f.time_zone_select :timezone , nil, { label: 'Time Zone'.t, required: true } %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= f.text_area :notes, rows: 4, label: 'Notes'.t %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= f.text_area :metadata, rows: 4, label: 'Metadata'.t %>
    </div>
  </div>

  <div class="form-row">
    <%= f.submit 'Submit'.t, class: 'btn btn-primary' %>&nbsp;
    <%= link_to((participant.team_diagnostic.participants.count > 1 ? 'Done' : 'Cancel').t, wizard_team_diagnostic_path(id: participant.team_diagnostic.id, step: TeamDiagnostics::Wizard::PARTICIPANTS_STEP), class: 'btn btn-light') %>
  </div>
<% end %>

app/views/participants/_participant.html.erb
<tr>
  <td><span class="badge badge-pill badge-<%= participant_state_badge_class(participant) %>"><%= participant.state %></span></td>
  <td class="text-nowrap"><%= participant.full_name %></td>
  <td>
    <%= mail_to(participant.email) %>
    <% if participant.phone %>
      &mdash;
      <%= participant.phone %>
    <% end %>
    <span class="badge badge-pill badge-light"><%= participant.locale %></span>
    <br/>
    <small><%= participant.notes %></small>
  </td>
  <td>
    <%= link_to('Edit'.t, edit_team_diagnostic_participant_path(team_diagnostic_id: participant.team_diagnostic_id, id: participant.id), class: 'btn btn-sm btn-primary') if policy(participant).edit? %>
    <%= link_to('Activate'.t, activate_team_diagnostic_participant_path(team_diagnostic_id: participant.team_diagnostic_id, id: participant.id), method: :post, data: { confirm: 'Are you sure?'.t }, class: 'btn btn-sm btn-success') if policy(participant).activate? %>
    <%= link_to('Resend Invitation'.t, resend_invitation_team_diagnostic_participant_path(team_diagnostic_id: participant.team_diagnostic_id, id: participant.id), method: :post, data: { confirm: 'Are you sure?'.t }, class: 'btn btn-sm btn-success') if policy(participant).resend_invitation? %>
    <%= link_to('Disqualify'.t, disqualify_team_diagnostic_participant_path(team_diagnostic_id: participant.team_diagnostic_id, id: participant.id), method: :post, data: { confirm: 'Are you sure?'.t }, class: 'btn btn-sm btn-warning') if policy(participant).disqualify? %>
    <%= link_to('Restore'.t, restore_team_diagnostic_participant_path(team_diagnostic_id: participant.team_diagnostic_id, id: participant.id), method: :post, class: 'btn btn-sm btn-success', data: { confirm: 'Are you sure?'.t }) if policy(participant).restore? %>
    <%= link_to('Remove'.t, team_diagnostic_participant_path(team_diagnostic_id: participant.team_diagnostic_id, id: participant.id), method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: 'Are you sure?'.t }) if policy(participant).destroy? %>
  </td>
</tr>

app/views/participants/_table.html.erb
<tr>
  <td><span class="badge badge-pill badge-info"><%= participant.state %></span></td>
  <td class="text-nowrap"><%= participant.full_name %></td>
  <td>
    <%= mail_to(participant.email) %>
    <% if participant.phone %>
      &mdash;
      <%= participant.phone %>
    <% end %>
    <span class="badge badge-pill badge-light"><%= participant.locale %></span>
    <br/>
    <small><%= participant.notes %></small>
  </td>
  <td>
    <%= link_to('Edit'.t, edit_team_diagnostic_participant_path(team_diagnostic_id: participant.team_diagnostic_id, id: participant.id), class: 'btn btn-sm btn-primary') if policy(participant).edit? %>
    <%= link_to('Disqualify'.t, disqualify_team_diagnostic_participant_path(team_diagnostic_id: participant.team_diagnostic_id, id: participant.id), method: :post, class: 'btn btn-sm btn-warning') if policy(participant).disqualify? %>
    <%= link_to('Restore'.t, restore_team_diagnostic_participant_path(team_diagnostic_id: participant.team_diagnostic_id, id: participant.id), method: :post, class: 'btn btn-sm btn-warning') if policy(participant).restore? %>
    <%= link_to('Remove'.t, team_diagnostic_participant_path(team_diagnostic_id: participant.team_diagnostic_id, id: participant.id), method: :delete, class: 'btn btn-sm btn-danger') if policy(participant).destroy? %>
  </td>
</tr>

app/views/participants/define_import.html.erb
<div class="row">
  <div clas="col">
    <%= render partial: 'breadcrumbs' %>
  </div>
</div>

<div class="row">
  <div class="col">
    <h1><%= 'Import Participants'.t %></h1>
  </div>
</div>


<% if @errors %>
  <div class="row alert alert-danger">
    <div class="col">
      <h4><%= 'There were problems importing Participants'.t %></h4>
      <% if @service.stats.present? %>
      <p class="lead">
        <ul>
          <% @service.errors.each do |error| %>
            <li><%= 'Error'.t %>: <%= error.t %></li>
          <% end %>
          <li><strong><%= 'Imported'.t %>: </strong><%= @service.stats[:created] %></li>
          <li><strong><%= 'Skipped'.t %>: </strong><%= @service.stats[:skipped] %></li>
          <li><strong><%= 'Errors'.t %>: </strong><%= @service.stats[:errors].size %></li>
        </ul>
      </p>
      <% end %>
      <div class="d-flex justify-content-center">
        <div class="">
          <table class="table">
            <thead>
              <tr>
                <th><%= 'Record'.t %></th>
                <th><%= 'Title'.t %></th>
                <th><%= 'First Name'.t %></th>
                <th><%= 'Last Name'.t %></th>
                <th><%= 'Email'.t %></th>
                <th><%= 'Phone Number'.t %></th>
                <th><%= 'Locale'.t %></th>
              </th>
            </thead>
            <tbody>
              <% @service.stats[:errors].each do |row| %>
                <tr>
                  <td><%= row + 1 %></td>
                  <% @service.rows[row].each do |col| %>
                    <td><%= col %></td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col">
    <p class="lead">
      <%= sanitize('team_diagnostic--participants--define_import-help'.t, tags: %w{ul li b strong}) %>
    </p>
  </div>
</div>

<div class="d-flex justify-content-center">
  <div class="">
    <table class="table">
      <thead>
        <tr>
          <th><%= 'Title'.t %></%=></th>
          <th><%= 'First Name'.t %></th>
          <th><%= 'Last Name'.t %></th>
          <th><%= 'Email'.t %></th>
          <th><%= 'Phone Number'.t %></th>
          <th><%= 'Locale'.t %></th>
        </th>
      </thead>
      <tbody>
        <tr>
          <td>Ms.</td>
          <td>Jane</td>
          <td>Smith</td>
          <td>jsmith@example.com</td>
          <td>+1 555-555-5555</td>
          <td>en</td>
        </tr>
        <tr>
          <td>Mr.</td>
          <td>John</td>
          <td>Doe</td>
          <td>jdoe@example.com</td>
          <td></td>
          <td>en</td>
        </tr>
        <tr>
          <td></td>
          <td>Pat</td>
          <td>Doe</td>
          <td>pdoe@example.com</td>
          <td></td>
          <td></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div clas="col">
    <%= form_tag(create_import_team_diagnostic_participants_path(team_diagnostic_id: @team_diagnostic.id), multipart: true, method: :post) do |f| %>
      <div class="form-group">
        <%= file_field_tag :participants, class: 'form-control-lg', id: 'participant_file_select' %>
      </div>
      <%= submit_tag('Import'.t, class: 'btn btn-primary', id: 'participant_import_submit', disabled: true) %>
      <%= link_to('Back'.t, :back, class: 'btn btn-light') %>
    <% end %>
  </div>
</div>

app/views/participants/edit.html.erb
<div class="row">
  <div clas="col">
    <%= render partial: 'breadcrumbs' %>
  </div>
</div>
<div class="row" id="new_participant">
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-12">
        <h1><%= 'Edit Participant'.t %></h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= render 'form', participant: @participant %>
      </div>
    </div>
  </div>
</div>

app/views/participants/index.html.erb
<div class="row">
  <div clas="col">
    <%= render partial: 'breadcrumbs' %>
  </div>
</div>

<div class="row">
  <div class="col">
    <h1>
      <%= @team_diagnostic.name %> &mdash; <%= 'Diagnostic Participants'.t %>
      <% if policy(@team_diagnostic).modify_participants?  %>
        <%= link_to('Add'.t, new_team_diagnostic_participant_path(team_diagnostic_id: @team_diagnostic.id), class: 'btn btn-sm btn-primary') %>
        <%= link_to('Import'.t, define_import_team_diagnostic_participants_path(team_diagnostic_id: @team_diagnostic.id), class: 'btn btn-sm btn-primary') %>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col">
    <table class="table shadow">
      <thead>
        <tr>
          <th><%= 'Status'.t %></th>
          <th><%= 'Name'.t %></th>
          <th><%= 'Contact'.t %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render @participants.order(last_name: :asc, first_name: :asc) %>
      </tbody>
    </table>

  </div>
</div>

app/views/participants/new.html.erb
<div class="row">
  <div clas="col">
    <%= render partial: 'breadcrumbs' %>
  </div>
</div>
<div class="row" id="new_participant">
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-12">
        <h1><%= 'Add Diagnostic Participant'.t %></h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= render 'form', participant: @participant %>
      </div>
    </div>
  </div>
</div>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Teamdiagnostic:</strong>
  <%= @participant.team_diagnostic_id %>
</p>

<p>
  <strong>State:</strong>
  <%= @participant.state %>
</p>

<p>
  <strong>Email:</strong>
  <%= @participant.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @participant.phone %>
</p>

<p>
  <strong>Title:</strong>
  <%= @participant.title %>
</p>

<p>
  <strong>First name:</strong>
  <%= @participant.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @participant.last_name %>
</p>

<p>
  <strong>Locale:</strong>
  <%= @participant.locale %>
</p>

<p>
  <strong>Timezone:</strong>
  <%= @participant.timezone %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @participant.notes %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>