config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  # TODO: - remove or add this line locally.
  # mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  authenticated :user, ->(user) { user.admin? } do
    mount DelayedJobWeb, at: '/delayed_job'
  end

  devise_for :users, path: :auth, controllers: { sessions: 'users/sessions',
                                                 confirmations: 'users/confirmations',
                                                 registrations: 'users/registrations',
                                                 unlocks: 'users/unlocks',
                                                 passwords: 'users/passwords' }

  get 'request_consent', to: 'home#request_consent'
  post 'grant_consent', to: 'home#grant_consent'
  get 'after_registration', to: 'home#after_registration'
  get 'system_events', to: 'home#system_events'

  resources :team_diagnostic_letters
  resources :diagnostics do
    resources :diagnostic_questions
  end
  resources :diagnostic_questions
  resources :entitlements
  resources :invitations do
    collection do
      get 'claim', to: 'invitations#claim'
      post 'process_claim', to: 'invitations#process_claim'
      post 'resend', to: 'invitations#resend'
    end
  end
  resources :organizations
  resources :tenants
  resources :translations, as: :application_translations, alias: :translations
  resources :users do
    resources :grants
  end
  resources :team_diagnostics do
    resources :participants do
      collection do
        get :define_import, to: 'participants#define_import'
        post :create_import, to: 'participants#create_import'
      end
      member do
        post :disqualify, to: 'participants#disqualify'
        post :restore, to: 'participants#restore'
        post :activate, to: 'participants#activate'
        post :resend_invitation, to: 'participants#resend_invitation'
      end
    end
    member do
      get 'wizard/:step', to: 'team_diagnostics#wizard', as: 'wizard'
      get 'export.:format', to: 'team_diagnostics#export', as: 'export'
      get 'report/:report_id.:format', to: 'team_diagnostics#report', as: 'report'
      post :deploy, to: 'team_diagnostics#deploy'
      post :complete, to: 'team_diagnostics#complete'
      post :generate_report, to: 'team_diagnostics#generate_report'
      delete :cancel, to: 'team_diagnostics#cancel'
    end
    resources :team_diagnostic_questions
    resources :team_diagnostic_letters
  end
  resources :participants
  resources :diagnostic_surveys do
    collection do
      get :not_found, to: 'diagnostic_surveys#not_found'
    end
    member do
      post :complete, to: 'diagnostic_surveys#complete'
    end
  end
  # Error pages
  %w[404 422 500].each do |code|
    get code, to: 'errors#show', code:
  end
end

app/models/concerns/users/devise.rb
# frozen_string_literal: true

module Users
  # User model class extension for Devise authentication
  module Devise
    extend ActiveSupport::Concern

    included do
      devise :database_authenticatable, :async, :registerable, :recoverable, :rememberable, :validatable, :confirmable, :lockable, :trackable

      def active?
        active_for_authentication?
      end
    end

    attr_accessor :login
  end
end

app/models/concerns/users/organizations.rb
# frozen_string_literal: true

module Users
  # User Organization Logic
  module Organizations
    extend ActiveSupport::Concern

    included do
      has_many :organization_memberships, class_name: 'OrganizationUser'
      has_many :organizations, through: :organization_memberships

      def organization_role(organization)
        organization_memberships
          .where(organization_id: organization.id)
          .first&.role
      end

      def organization_membership_date(organization)
        organization_memberships
          .where(organization_id: organization.id)
          .first&.created_at
      end
    end
  end
end

app/models/concerns/users/profiles.rb
# frozen_string_literal: true

module Users
  # User Profile Extensions
  module Profiles
    extend ActiveSupport::Concern

    included do
      has_one :user_profile, dependent: :destroy
      accepts_nested_attributes_for :user_profile, update_only: true

      def name
        return email unless user_profile.present?

        [user_profile.prefix, user_profile.first_name, user_profile.middle_name, user_profile.last_name, user_profile.suffix].compact.join(' ').gsub(/ +/, ' ').strip
      end

      def pronoun
        user_profile&.pronoun
      end

      def country_name
        user_profile&.country_name || ''
      end

      def required_consent_pending?
        user_profile ? user_profile.required_consent_pending? : true
      end

      def required_consents_pending
        user_profile ? user_profile.required_consents_pending : []
      end

      def consent_granted?(key)
        user_profile ? user_profile.consent_granted?(key) : true
      end

      def consent_revoked?(key)
        user_profile ? user_profile.consent_revoked?(key) : true
      end

      def update_consents(params)
        user_profile ? user_profile.update_consents(params) : false
        save
      end

      def revoke_consent(key)
        user_profile ? user_profile.revoke_consent(key) : false
        save
      end
    end
  end
end

app/models/concerns/users/roles.rb
# frozen_string_literal: true

module Users
  # User model class extension for Role features
  module Roles
    extend ActiveSupport::Concern

    included do
      belongs_to :role

      delegate :admin?, :staff?, :translator?, :facilitator?, :member?, to: :role
    end

    class_methods do
      def admins
        includes(:role).where(roles: { slug: Role::ADMIN_ROLE })
      end

      def staff
        includes(:role).where(roles: { slug: Role::STAFF_ROLE })
      end

      def translators
        includes(:role).where(roles: { slug: Role::STAFF_ROLE })
      end

      def facilitators
        includes(:role).where(roles: { slug: Role::FACILITATOR_ROLE })
      end

      def members
        includes(:role).where(roles: { slug: Role::MEMBER_ROLE })
      end
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

# Devise overrides for Users Confirmations Controller
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  def show
    super do |resource|
      # Special handling of already confirmed users visiting
      # the confirmation link
      if resource.confirmed_at.present?
        if resource.encrypted_password?
          # Confirmed but password not set. Set password.
          redirect_to root_url
        else
          # Confirmed and password set means go to login
          redirect_to new_user_password_path(resource)
        end
        return
      end
    end
  end

  def user_set_password_path(resource)
    token = resource.send(:set_reset_password_token)
    edit_password_url(resource, reset_password_token: token)
  end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

# See: https://raw.githubusercontent.com/heartcombo/devise/master/app/controllers/devise/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    invitation
    assign_invitation_locale
    build_resource
    resource.role = Role.facilitator
    yield resource if block_given?
    respond_with resource
  end

  # POST /resource
  def create
    invitation
    authorizer
    assign_invitation_locale

    allowed_params = User::ALLOWED_PARAMS + [{ user_profile_attributes: UserProfile::ALLOWED_PARAMS }]
    custom_sign_up_params = params.require(:user).permit(*allowed_params)

    build_resource(custom_sign_up_params)
    resource.role = authorizer.invitation_role
    resource.tenant = current_tenant
    resource.save

    if resource.persisted?
      EntitlementServices::InvitationClaim.new(tenant: @current_tenant, token: @invitation.token, user: resource).call
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  def edit
    # super
    raise 'Unsupported'
  end

  # PUT /resource
  def update
    # super
    raise 'Unsupported'
  end

  # DELETE /resource
  def destroy
    # super
    raise 'Unsupported'
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # def sign_up_params
  # allowed_params = [ :username, :email, :password, :password_confirmation, :locale, :timezone, {
  # user_profile_attributes: [:prefix, :first_name, :middle_name, :last_name, :pronoun, :title, :department, :company, :country] }
  # ]
  # params.require(:user).permit(*allowed_params)
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end
  def after_sign_up_path_for(_resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def after_inactive_sign_up_path_for(_resource)
    after_registration_path
  end

  # Require a valid and unclaimed invitation for the current tenant
  def invitation
    @invitation ||= begin
      required_entitlement = Entitlement.where(slug: Entitlement::REGISTER_AS_FACILITATOR).first
      raise ActiveRecord::RecordNotFound unless required_entitlement.present?

      @current_tenant.invitations.unclaimed.find(params[:invitation_id])
    end
  end

  def authorizer
    invitation
    params[:token] = @invitation.token
    authorizer = EntitlementServices::Authorizer.new(user: nil, params:, tenant: @current_tenant, reference: 'Users::Registrations#')
    raise ActiveRecord::RecordNotFound unless authorizer.call

    authorizer
  end

  def assign_invitation_locale
    invitation
    I18n.locale = @invitation&.locale || 'en'
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

# Devise Sessions Controller
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end
  def new
    @page_title = 'Log in'.t
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# User Management Controller
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update destroy]
  after_action :verify_authorized

  def index
    authorize User
    search = UserServices::Search.new(params, policy_scope(User), current_user)
    @users = search.call
    @page_title = 'Manage User Accounts'.t
    @current_page = 'All'.t
  end

  def new
    authorize User
    @user = User.new(tenant: current_tenant, user_profile: UserProfile.new)
    @show_validation_messages = false
    @current_page = @page_title = 'New User Account'.t
  end

  def create
    authorize User
    @user = User.new(user_params)
    @user.tenant = current_tenant
    @invalid = false
    respond_to do |format|
      if @user.save
        format.html { redirect_to user_path(@user), notice: 'User was created'.t }
      else
        format.html { render :new, notice: 'There were problems'.t }
      end
    end
  end

  def show
    authorize @user
    @current_page = @user.name
  end

  def edit
    authorize @user
    @page_title = 'Edit User Account'.t
    @current_page = @user.name
  end

  def update
    authorize @user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_path(@user), notice: 'User account updated'.t }
      else
        format.html { render :edit, notice: 'There were problems'.t }
      end
    end
  end

  # Lock User Account
  def destroy
    authorize @user
    if params[:unlock].present? && @user.locked?
      @user.unlock_access!
      notice = 'User was unlocked'.t
    else
      @user.lock_access!
      notice = 'User was locked'.t
    end
    respond_to do |format|
      format.html { redirect_to users_path, notice: }
    end
  end

  private

  def user_params
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    # Protect against privilege escalation
    if params[:user][:role_id].present?
      new_role = Role.where(id: params[:user][:role_id]).first
      params[:user].delete(:role_id) unless new_role && current_user.role >= new_role
    end
    allowed_params = policy(@user || User).allowed_params
    params.require(:user).permit(allowed_params)
  end

  def set_user
    @user = policy_scope(User).find(params[:id])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# View Helper
module UsersHelper
  def roles_for_select(user = nil)
    roles = [Role.admin, Role.staff, Role.translator, Role.facilitator, Role.member]
            .select { |r| current_user.role >= r }
    options_for_select(roles.map { |r| [r.name, r.id] }, user&.role_id)
  end

  def locales_for_select(user = nil)
    locales = GlobalizeLanguage.order(:english_name).map { |l| [l.english_name.t, l.iso_639_1] }
    options_for_select(locales, user&.locale)
  end

  def countries_for_select(user_profile = nil)
    countries = [['United States of America'.t, 'US']] + GlobalizeCountry.order(:english_name).map { |c| [c.english_name.t, c.code] }
    options_for_select(countries, user_profile&.country)
  end
end

app/views/users/_form.html.erb
<%= bootstrap_form_for(user, remote: false) do |form| %>
  <% if user.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only"><%= 'Close'.t %></span></button>
      <h4><%= 'Errors prevented changes from being saved'.t %>.</h4>

      <ul>
      <% user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <fieldset>
    <legend><%= 'Account'.t %></legend>
    <div class="form-row">
      <div class="col-sm-6">
        <%= form.text_field :username, label: 'Username'.t, required: true %>
      </div>
      <div class="col-sm-6">
        <%= form.select :role_id, roles_for_select(user), label: 'Role'.t, required: true, include_blank: true%>
      </div>
    </div>
    <%= form.email_field :email, label: 'Email'.t, required: true %>
    <div class="form-row">
      <div class="col-sm-6">
        <%= form.password_field :password, label: 'Password'.t, required: user.new_record?, autocomplete: 'new-password' %>
      </div>
      <div class="col-sm-6">
        <%= form.password_field :password_confirmation, label: 'Password Confirmation'.t, required: user.new_record?, autocomplete: 'new-password' %>
      </div>
    </div>
    <div class="form-row">
      <div class="col-sm-4">
        <%= form.select :locale, locales_for_select(user), label: 'Locale'.t, required: true %>
      </div>
      <div class="col-sm-8">
        <%= form.time_zone_select :timezone , nil, { label: 'Timezone'.t, required: true } %>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend><%= 'Profile'.t %></legend>
    <%= fields_for 'user[user_profile_attributes]', user.user_profile do |profile| %>
      <div class="form-row">
        <div class="col-sm-12 form-group">
          <%= profile.label :company, 'Company'.t %>
          <%= profile.text_field :company, class: 'form-control' %>
        </div>
      </div>
      <div class="form-row">
        <div class="col-sm-6 form-group">
          <%= profile.label :title, 'Position/Title'.t %>
          <%= profile.text_field :title, class: 'form-control' %>
        </div>
        <div class="col-sm-6 form-group">
          <%= profile.label :department, 'Department'.t %>
          <%= profile.text_field :department, class: 'form-control' %>
        </div>
      </div>
      <div class="form-row">
        <div class="col-sm-2 form-group">
          <%= profile.label :prefix, 'Prefix'.t %>
          <%= profile.text_field :prefix, class: 'form-control' %>
        </div>
        <div class="col-sm-3 form-group">
          <%= profile.label :first_name, 'First Name'.t %>
          <%= profile.text_field :first_name, class: 'form-control' %>
        </div>
        <div class="col-sm-2 form-group">
          <%= profile.label :middle_name, 'Middle'.t %>
          <%= profile.text_field :middle_name, class: 'form-control' %>
        </div>
        <div class="col-sm-3 form-group">
          <%= profile.label :last_name, 'Last Name'.t %>
          <%= profile.text_field :last_name, class: 'form-control', required: true %>
        </div>
        <div class="col-sm-2 form-group">
          <%= profile.label :pronoun, 'Pronoun'.t, required: true %>
          <%= profile.select :pronoun, options_for_select([['They'.t, 'they'],['He'.t, 'he'], ['She'.t,'she']], user.user_profile&.pronoun), {}, class: 'form-control' %>
        </div>
      </div>
      <div class="form-row">
        <div class="col-sm-6 form-group">
          <%= profile.label :country, 'Country'.t %>
          <%= profile.select :country, countries_for_select(user.user_profile), { allow_blank: false }, { class: 'form-control' } %>
        </div>
        <div class="col-sm-6 form-group">
          <%= profile.label :phone_number, 'Phone Number'.t %>
          <%= profile.text_field :phone_number, type: 'tel', class: 'form-control', required: true %>
        </div>
      </div>
      <% if policy(user).edit_staff_notes? %>
        <div class="form-row">
          <div class="col">
            <%= profile.label :staff_notes, 'Staff Notes'.t %>
            <%= profile.text_area :staff_notes, { rows: 4 ,class: 'form-control', aria: {describedby: 'staff_notes_helpblock'} } %>
            <small id="staff_notes_helpblock" class="form-text text-muted"><%= 'Only visible to staff'.t %></small>
          </div>
        </div>
      <% end %>
      <% if policy(user).admin_preferences? %>
        <div class="row m-2 p-2 bg-light">
          <div class="col">
            <h5>Admin Preferences</h5>
            <div class="form-row border">
              <div class="col">
                <%= profile.check_box :notification_admin_errors %>
                <%= profile.label :notification_admin_errors, 'System Error Notifications'.t %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </fieldset>

  <fieldset>
    <legend>
      <%= 'Consent'.t %>
      <%= link_to('View Agreements'.t, request_consent_path, class: 'btn btn-sm btn-info') %>
    </legend>
      <p class="lead">
        <strong><%= 'Permits the use of website cookies'.t %></strong>
        <span class="badge badge-<%= @user.consent_granted?(:cookies_required) ? 'success' : 'warning' %>">
          <%= @user.consent_granted?('cookies_required') ? 'Yes'.t : 'No'.t %>
        </span><br/>
        <strong><%= 'Accepts the website terms and conditions'.t %></strong>
        <span class="badge badge-<%= @user.consent_granted?(:eula) ? 'success' : 'warning' %>">
          <%= @user.consent_granted?('eula') ? 'Yes'.t : 'No'.t %>
        </span>
      </p>
  </fieldset>

  <div class="form-row">
    <%= form.submit 'Submit'.t, class: 'btn btn-success' %>
    <%= link_to('Cancel'.t, :back, class: 'btn btn-sm btn-light') %>
  </div>
<% end %>

app/views/users/_grants_card.html.erb
<% if policy(user).manage_grants? %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">
        <%= 'Grants'.t %>
        <small><%= link_to('Add'.t, new_user_grant_path(user), class: 'btn btn-sm btn-primary') %></small>
      </h5>
      <p class="card-text">
        <% if user.grants.any? %>
          <% user.grants.each do |grant| %>
            <p>
              <span class="badge badge-<%= grant.effective? ? 'success' : 'secondary' %>"><%= grant.effective? ? 'Active'.t : 'Inactive'.t %></span>
              <strong><%= grant.entitlement.description %></strong>
              <span class="badge badge-<%= grant.over_quota? ? 'warning' : 'success' %>"><%= grant.usage_count %>/<%= grant.quota %></span>
              <%= grant.description %></small>
            <small><%= grant.staff_notes %></small>
            &mdash;
            <span class="text-nowrap">
              <%= link_to('Edit'.t, edit_user_grant_path(user, grant), class: 'badge badge-primary') %>
              <% if grant.active? %>
                <%= link_to('Deactivate'.t, user_grant_path(user_id: user.id, id: grant.id, deactivate: true), method: :delete, data: { confirm: 'Are you sure?'.t }, class: 'badge badge-warning') %>
              <% else %>
                <%= link_to('Remove'.t, user_grant_path(user, grant), method: :delete, data: { confirm: 'Are you sure?'.t }, class: 'badge badge-danger') %>
              <% end %>
            </span>
          </p>
        <% end %>
      <% else %>
        <strong><%= 'None'.t %>
      <% end %>
    </p>
  </div>
</div>
<% end %>

app/views/users/_organizations_card.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">
      <%= 'Organizations'.t %>
    </h5>
    <p class="card-text">
      <% user.organizations.each do |organization| %>
        <p class="lead">
        <%= link_to(organization.name, organization_path(organization)) %>
        </p>
        <ul>
          <% organization.team_diagnostics.each do |diagnostic| %>
            <li>
              <%= render partial: 'team_diagnostics/team_diagnostic', locals: { diagnostic: diagnostic } %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </p>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div clas="col">
    <%= render partial: 'breadcrumbs' %>
  </div>
</div>

<div class="row">
  <div class="col">
    <h1><%= 'Manage User Accounts'.t %>
    <small><%= link_to('Add'.t, new_user_path, class: 'btn btn-sm btn-success') %></small>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table shadow users--table">
      <thead>
        <tr>
          <th><%= 'Login'.t %></th>
          <th><%= 'Locale'.t %>/<%='Time Zone'.t %></th>
          <th><%= 'Status'.t %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <strong>Username:</strong> <%= user.username %><br/>
              <strong>Email:</strong> <%= link_to(user.email, 'mailto://' + user.email, target: '_blank') %>
            </td>
            <td>
              <strong><%= user.locale %></strong>
              <span class="text-nowrap"><%= user.timezone %></span>
            </td>
            <td>
              <p class="text-nowrap">
                <span class="badge badge-info"><%= user.role.name.t %></span>
                <span class="badge badge-<%= user.locked? ? 'danger' : 'success' %>"><%= user.locked? ? 'Locked'.t : 'Active'.t %></span>
                <span class="badge badge-<%= user.confirmed? ? 'success' : 'warning' %>"><%= user.confirmed? ? 'Confirmed'.t : 'Unconfirmed'.t %></span>
                <br/>
                <strong><%= 'Created'.t %>:</strong> <span class="text-nowrap"><%= l(user.created_at, format: :long) %></span><br/>
                <strong><%= 'Confirmed'.t %>:</strong> <span class="text-nowrap"><%= user.confirmed? ? l(user.confirmed_at, format: :long) : 'No'.t  %></span><br/>
                <strong><%= 'Locked'.t %>:</strong> <span class="text-nowrap"><%= user.locked? ? l(user.locked_at, format: :long) : 'No'.t  %></span><br/>
              </p>
              <% if policy(user).edit_staff_notes? %>
                <p>
                  <small class="text-muted"><%= user.user_profile&.staff_notes %></small>
                </p>
              <% end %>
            </td>
            <td>
              <p>
                <%= link_to('More'.t, user_path(user), class: 'btn btn-sm btn-info') %>
                <%= link_to('Edit'.t, edit_user_path(user), class: 'btn btn-sm btn-primary') if policy(user).edit? %>
                <% if user.locked? %>
                  <%= link_to('Unlock'.t, user_path(user, unlock: true), method: :delete, class: 'btn btn-sm btn-warning', data: { confirm: 'Are you sure you want to unlock this account?'.t } ) %>
                <% else %>
                  <%= link_to('Lock'.t, user_path(user), method: :delete, class: 'btn btn-sm btn-warning', data: { confirm: 'Are you sure you want to lock this account?'.t } ) %>
                <% end if policy(user).destroy? %>
              </p>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div clas="col">
    <%= render partial: 'breadcrumbs' %>
  </div>
</div>
<div class="row">
  <div class="col">
    <h1><%= 'Create New User'.t %></h1>
  </div>
</div>

<div class="row">
  <div class="col">
    <%= render partial: 'form', locals: { user: @user } %>
  </div>
</div>