config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  # TODO: - remove or add this line locally.
  # mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  authenticated :user, ->(user) { user.admin? } do
    mount DelayedJobWeb, at: '/delayed_job'
  end

  devise_for :users, path: :auth, controllers: { sessions: 'users/sessions',
                                                 confirmations: 'users/confirmations',
                                                 registrations: 'users/registrations',
                                                 unlocks: 'users/unlocks',
                                                 passwords: 'users/passwords' }

  get 'request_consent', to: 'home#request_consent'
  post 'grant_consent', to: 'home#grant_consent'
  get 'after_registration', to: 'home#after_registration'
  get 'system_events', to: 'home#system_events'

  resources :team_diagnostic_letters
  resources :diagnostics do
    resources :diagnostic_questions
  end
  resources :diagnostic_questions
  resources :entitlements
  resources :invitations do
    collection do
      get 'claim', to: 'invitations#claim'
      post 'process_claim', to: 'invitations#process_claim'
      post 'resend', to: 'invitations#resend'
    end
  end
  resources :organizations
  resources :tenants
  resources :translations, as: :application_translations, alias: :translations
  resources :users do
    resources :grants
  end
  resources :team_diagnostics do
    resources :participants do
      collection do
        get :define_import, to: 'participants#define_import'
        post :create_import, to: 'participants#create_import'
      end
      member do
        post :disqualify, to: 'participants#disqualify'
        post :restore, to: 'participants#restore'
        post :activate, to: 'participants#activate'
        post :resend_invitation, to: 'participants#resend_invitation'
      end
    end
    member do
      get 'wizard/:step', to: 'team_diagnostics#wizard', as: 'wizard'
      get 'export.:format', to: 'team_diagnostics#export', as: 'export'
      get 'report/:report_id.:format', to: 'team_diagnostics#report', as: 'report'
      post :deploy, to: 'team_diagnostics#deploy'
      post :complete, to: 'team_diagnostics#complete'
      post :generate_report, to: 'team_diagnostics#generate_report'
      delete :cancel, to: 'team_diagnostics#cancel'
    end
    resources :team_diagnostic_questions
    resources :team_diagnostic_letters
  end
  resources :participants
  resources :diagnostic_surveys do
    collection do
      get :not_found, to: 'diagnostic_surveys#not_found'
    end
    member do
      post :complete, to: 'diagnostic_surveys#complete'
    end
  end
  # Error pages
  %w[404 422 500].each do |code|
    get code, to: 'errors#show', code:
  end
end

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= flash_alert_class(type) %> alert-dismissable" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only"><%= 'Close'.t %></span></button>
    <%= msg.t %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
  <% if false %>
    <!-- 
      <% if user_signed_in? %>
        <% cache([ @current_user || 'unknown', 'footer' ]) do %>
          <li class="nav-item"><%= link_to('Dashboard'.t, root_path, class: 'nav-link px-2 text-muted') %></li>
          <% if policy(TeamDiagnostic).index? %>
            <li class="nav-item"><%= link_to('Diagnostics'.t, team_diagnostics_path, class: 'nav-link px-2 text-muted') %></li>
          <% end %>
        <% end %>
      <% end %>
    -->
    <% end %>
    </ul>
    <p class="text-center text-muted">&copy;<%= Date.current.year %> Team Coaching International. All Rights Reserved.</p>
  </footer>

app/views/shared/_form_errors.html.erb
<% if subject.errors.any? %>
  <div class="alert alert-danger alert-dismissable" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only"><%= 'Close'.t %></span></button>
    <h4><%= 'Errors prohibited changes from being saved'.t %>.</h4>

    <ul>
    <% subject.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_login_items.html.erb
<% if user_signed_in? %>
  <%= link_to('Profile'.t, edit_user_path(current_user)) %>
  <%= link_to('Logout'.t, destroy_user_session_path, method: :delete) %>
<% else %>
  <%= link_to('Login'.t, new_user_session_path) unless controller.controller_name == 'sessions' %>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
  <a class="navbar-brand" href="/">
    <%= image_tag 'tci_logo.png', height: '50px' %>
    <h5 class="text-center">Team Diagnostic&trade;</h5>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">

      <% if user_signed_in? %>
        <% cache([ @current_user || 'unknown', 'nav' ]) do %>
          <% if policy(Invitation).index? %>
            <li class="nav-item <%= nav_item_class(:invitations) %>">
              <%= link_to('Invitations'.t, invitations_path, class: 'nav-link')  %>
            </li>
          <% end %>
          <% if policy(User).index? %>
            <li class="nav-item <%= nav_item_class(:users) %>">
              <%= link_to('Users'.t, users_path, class: 'nav-link')  %>
            </li>
          <% end %>
          <% if policy(TeamDiagnostic).index? %>
            <li class="nav-item <%= nav_item_class(:team_diagnostics) %>">
              <%= link_to('Diagnostics'.t, team_diagnostics_path, class: 'nav-link')  %>
            </li>
          <% end %>
          <% if policy(Organization).index? %>
            <li class="nav-item <%= nav_item_class(:organizations) %>">
              <%= link_to('Organizations'.t, organizations_path, class: 'nav-link')  %>
            </li>
          <% end %>
          <% if @current_user.admin? || @current_user.translator? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbar--system-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= 'System'.t %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbar--system-dropdown">
                <% if policy(Entitlement).index? %>
                  <%= link_to('Entitlements'.t, entitlements_path, class: 'dropdown-item')  %>
                <% end %>
                <% if policy(Diagnostic).index? %>
                  <%= link_to('Diagnostics'.t, diagnostics_path, class: 'dropdown-item')  %>
                <% end %>
                <% if policy(Tenant).index? %>
                  <%= link_to('Tenants'.t, tenants_path, class: 'dropdown-item')  %>
                <% end %>
                <% if policy(ApplicationTranslation).index? %>
                  <%= link_to('Translations'.t, application_translations_path(tlocale: @current_locale || 'en'), class: 'dropdown-item')  %>
                <% end %>
                <% if policy(:home).system_events? %>
                  <%= link_to('System Events'.t, system_events_path(tlocale: @current_locale || 'en'), class: 'dropdown-item')  %>
                <% end %>
              </div>
            </li>
          <% end %>
          <li class="nav-item <%= nav_item_class(:users, :edit) %>">
            <%= link_to('Profile'.t, edit_user_path(current_user), class: 'nav-link') %>
          </li>
          <li class="nav-item">
            <%= link_to('Logout'.t, destroy_user_session_path, method: :delete, class: 'nav-link') %>
          </li>
        <% end %>
      <% else %>
        <li class="nav-item">
          <%= link_to('Login'.t, new_user_session_path, class: 'nav-link') if show_login_link? %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>
<br/>