config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  # TODO: - remove or add this line locally.
  # mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  authenticated :user, ->(user) { user.admin? } do
    mount DelayedJobWeb, at: '/delayed_job'
  end

  devise_for :users, path: :auth, controllers: { sessions: 'users/sessions',
                                                 confirmations: 'users/confirmations',
                                                 registrations: 'users/registrations',
                                                 unlocks: 'users/unlocks',
                                                 passwords: 'users/passwords' }

  get 'request_consent', to: 'home#request_consent'
  post 'grant_consent', to: 'home#grant_consent'
  get 'after_registration', to: 'home#after_registration'
  get 'system_events', to: 'home#system_events'

  resources :team_diagnostic_letters
  resources :diagnostics do
    resources :diagnostic_questions
  end
  resources :diagnostic_questions
  resources :entitlements
  resources :invitations do
    collection do
      get 'claim', to: 'invitations#claim'
      post 'process_claim', to: 'invitations#process_claim'
      post 'resend', to: 'invitations#resend'
    end
  end
  resources :organizations
  resources :tenants
  resources :translations, as: :application_translations, alias: :translations
  resources :users do
    resources :grants
  end
  resources :team_diagnostics do
    resources :participants do
      collection do
        get :define_import, to: 'participants#define_import'
        post :create_import, to: 'participants#create_import'
      end
      member do
        post :disqualify, to: 'participants#disqualify'
        post :restore, to: 'participants#restore'
        post :activate, to: 'participants#activate'
        post :resend_invitation, to: 'participants#resend_invitation'
      end
    end
    member do
      get 'wizard/:step', to: 'team_diagnostics#wizard', as: 'wizard'
      get 'export.:format', to: 'team_diagnostics#export', as: 'export'
      get 'report/:report_id.:format', to: 'team_diagnostics#report', as: 'report'
      post :deploy, to: 'team_diagnostics#deploy'
      post :complete, to: 'team_diagnostics#complete'
      post :generate_report, to: 'team_diagnostics#generate_report'
      delete :cancel, to: 'team_diagnostics#cancel'
    end
    resources :team_diagnostic_questions
    resources :team_diagnostic_letters
  end
  resources :participants
  resources :diagnostic_surveys do
    collection do
      get :not_found, to: 'diagnostic_surveys#not_found'
    end
    member do
      post :complete, to: 'diagnostic_surveys#complete'
    end
  end
  # Error pages
  %w[404 422 500].each do |code|
    get code, to: 'errors#show', code:
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Dashboard/root Controller
class HomeController < ApplicationController
  before_action :authenticate_user!, except: %i[after_registration]
  skip_before_action :authorize_consent!, only: %i[request_consent grant_consent after_registration]
  after_action :verify_authorized

  def index
    authorize :home, :index?
    @page_title = 'TeamDiagnostic Home'.t
    render roled_dashboard_partial_name
  end

  def request_consent
    authorize :home, :request_consent?
    @page_title = 'User Agreements and Consent'.t
    @pending = UserProfile::REQUIRED_CONSENTS
  end

  def grant_consent
    authorize :home, :grant_consent?
    current_user.update_consents(params)
    flash[:notice] = 'Your preferences were updated'.t
    redirect_to root_path
  end

  def after_registration
    authorize :home, :after_registration?
    @page_title = 'Thank you for registering'.t
  end

  def system_events
    authorize :home, :system_events?
    @page_title = 'System Events'
    # Errors from the past two days (minutes)
    @days = 30
    @system_events = SystemEvent.notifiable.recent(60 * 24 * @days).order(created_at: :desc)
  end

  private

  def roled_dashboard_partial_name
    "index_#{@current_user.role&.slug || 'default'}"
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# Misc view helpers
module HomeHelper
end

app/views/home/_consent_cookies_required_en.html.erb
<p class="lead">
  TeamDiagnostic uses website cookies to ensure correct function and personalization.
</p>

<p class="alert-success">
  We do not use tracking cookies or any other 3rd party cookies used for the purpose of
  collecting your personal information or tracking your behavior.
</p>

<p class="lead"> 
  With this in mind, I accept the use of cookies on TeamDiagnostic.com:
</p>

app/views/home/_consent_eula_en.html.erb
<p class="lead">
  TeamDiagnostic.com is a service provided by Team Coaching International.
</p>

<p class="alert-success">
  We promise to respect your privacy.
</p>

<p class="lead alert-warning">
  I promise to not use this service to commit any crimes, harass others, or otherwise negatively impact
  this site, its users, or its administrators and owners.
</p>

app/views/home/_organization.html.erb
<div class="card mx-auto organization-card shadow-sm">
  <div class="card-body">
    <h2 class="card-title">
      <%= organization.name %>
      <%= link_to('More'.t, organization_path(organization), class: 'btn btn-sm btn-info') %>
    </h5>
    <%= render partial: 'organizations/team_diagnostics', locals: { organization: organization } %>
  </div>
</div>
<br/>

app/views/home/_organization_team_diagnostics.html.erb
  <% if organization.team_diagnostics.any? %>
    <h4>
      <%= 'Team Diagnostics'.t %>
      <%= link_to('New'.t, new_team_diagnostic_path, class: 'btn btn-sm btn-primary') %>
    </h4>
    <% TeamDiagnosticPolicy::Scope.new(current_user, organization.team_diagnostics).resolve.order(created_at: :desc).each do |diagnostic| %>
      <p>
        <span class="badge badge-pill badge-<%= team_diagnostic_state_pill_class(diagnostic) %>"><%= diagnostic.state.t %></span>
        <span class="badge badge-light"><%= diagnostic.diagnostic.slug %></span>
        <%= link_to wizard_team_diagnostic_path(id: diagnostic.id, step: diagnostic.wizard)  do %>
          <%= diagnostic.name %>
        <% end %>
        <small><%= diagnostic.due_at.strftime('%B %d, %Y') %></small>
      </p>
    <% end %>
  <% else %>
    <%= link_to('Create your first Team Diagnostic'.t, new_team_diagnostic_path, class: 'btn btn-lg btn-success') if policy(TeamDiagnostic).new? %>
  <% end %>

app/views/home/_organizations.html.erb
<% if @current_user.organizations.any? %>
  <%= render collection: @current_user.organizations.order(name: :desc), partial: 'organization' %>
<% else %>
  <p class="lead">
    Now that you are registered, your next step is to create an Organization.
    <hr class="my-4">
    <%= link_to('Continue'.t, new_organization_path, class: 'btn btn-lg btn-success') %>
  </p>
<% end %>

app/views/home/_profile_card.html.erb
<div class="card shadow-sm">
  <div class="card-body">
    <h5 class="card-title">
      <%= 'Profile'.t %>
      <%= link_to('Edit'.t, edit_user_path(user), class: 'btn btn-sm btn-primary' ) %>
    </h5>
    <p class="card-text">
      <%= user.name %>
      <span class="badge badge-light"><%= user.role.name.t %></span><br/>
      <strong><%= user.email %></strong><br/>
    </p>
  </div>
</div>

app/views/home/_system_events.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Time</th>
      <th>Severity</th>
      <th>Source/Incidental</th>
      <th>Description</th>
      <th>Incidental</th>
      <th>Debug</th>
    </tr>
  </thead>
  <tbody>
    <% system_events.each do |event| %>
      <tr>
        <td class="text-nowrap"><%= event.created_at.strftime("%m/%d/%y %H:%M") %></td>
        <td>
          <span class="badge rounded-pill bg-<%= severity_class(event.severity) %>">
            <%= event.severity %>
          </span>
        </td>
        <td>
          <p>
            <b>Source:</b>
            <%= link_to(event.event_source_type, ( url_for(event.event_source) rescue '#' )) %>
            &mdash;
            <%= event.event_source.name rescue '' %>
          </p>
          <% if event.incidental.present? %>
            <hr/>
            <p>
              <b>Incidental:</b>
              <%= link_to(event.incidental_type, url_for(event.incidental)) %>
              &mdash;
              <%= event.incidental.name rescue '' %>
            </p>
          <% end %>
        </td>
        <td><p><%= event.description %></p></td>
        <td>
          <tt>
            <%= truncate(event.debug, length: 300) %>
          </tt>
        </td>
      </tr>  
    <% end %>
  </tbody>
</table>

app/views/home/after_registration.html.erb
<div class="row">
  <div class="col">
    <div class="card">
      <h5 class="card-header"><%= 'Thank you for registering!'.t %></h5>
      <div class="card-body">
        <h5 class="card-title"><%= 'Please Wait'.t %></h5>
        <p class="card-text">
          <%= 'We are setting up your account.'.t %><br/>
          <%= 'A message will soon appear in your email inbox with a link to confirm your email address'.t %>
        </p>
        <%= link_to('Login'.t, new_user_session_path, class: 'btn btn-primary') %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home</h1>

<h2><%= current_tenant&.name || 'Unaffiliated User!'.t %> </h2>

<p>
  Host: <%= request.host %>
</p>
<p>
  Org: <%= @current_tenant&.name %>
</p>

app/views/home/index_admin.html.erb
<div class="row">
  <div class="col-lg-12 jumbotron bg-white shadow">
    <div class="row">
      <div class="col-sm-8">
        <h1 class="display-4"><%= 'Welcome %{name}'.t(name: @current_user.user_profile.first_name || @current_user.name) %></h1>
        <p class="lead">
          This is your TeamDiagnostic Application Dashboard.
        </p>
      </div>
      <div class="col-sm-4">
        <%= render partial: 'profile_card', locals: { user: @current_user } %>
      </div>
    </div>
  </div>
</div>

app/views/home/index_default.html.erb
<div class="row">
  <div class="col-md-12 jumbotron">
    <h1 class="display-4"><%= 'Welcome %{name}'.t(name: @current_user.name) %></h1>
  </div>
</div>

app/views/home/index_facilitator.html.erb
<div class="row">
  <div class="col-lg-12 jumbotron shadow bg-white">
    <div class="row">
      <div class="col-sm-8">
        <% if true || current_user_has_no_organizations_or_diagnostics? %>
          <h1 class="display-5"><%= 'Welcome %{name}'.t(name: @current_user.user_profile.first_name || @current_user.name) %></h1>
        <% end %>
        <p class="lead">
          <%= sanitized_translation 'dashboard-intro' if true || current_user_has_no_organizations_or_diagnostics? %>
        </p>
      </div>
      <div class="col-sm-4">
        <%= render partial: 'profile_card', locals: { user: @current_user } %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <p class="lead">
          <%= render partial: 'organizations' %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/home/request_consent.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <p class="lead">
        <%= 'consent-header-text'.t  %>
      </p>
    </div>
  </div>
  <%= form_tag(grant_consent_path, method: :post, remote: false) do %>
    <% @pending.each do |consent| %>
      <div class="row">
        <div class="col">
          <br/>
          <div class="card">
            <!-- <img src="..." class="card-img-top" alt="..."> -->
            <div class="card-body">
              <h5 class="card-title"><%= consent.humanize.titlecase %></h5>
              <div class="card-text">
                <% begin %>
                  <%= render partial: "consent_#{consent}_#{current_locale}" %>
                <% rescue %>
                  <%= render partial: "consent_#{consent}_en" %>
                <% end %>
                <hr/>
                <div class="row">
                  <div class="col-sm-4">
                    <div class="form-group custom-control custom-switch consent-switch">
                      <%= hidden_field_tag consent.to_sym, '0' %>
                      <%= check_box_tag consent.to_sym, '1', current_user.consent_granted?(consent), class: 'custom-control-input', id: "#{consent}_checkbox" %>
                      <label class="custom-control-label" for="<%= consent %>_checkbox"><%= 'I agree'.t %></label>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <br/>
    <%= submit_tag 'Submit'.t, class: "btn btn-success" %>
  <% end %>
</div>

app/views/home/system_events.html.erb
<div class="row">
  <div class="col">
    <h1>Errors (Past <%= @days %> days)</h1>
  </div>
</div>

<div class="row">
  <div class="col">
    <%= render partial: 'system_events', locals: { system_events: @system_events } %>
  </div>
</div>